pytorch 2.1.0
pytorch: update resources

Signed-off-by: Rui Chen <rui@chenrui.dev>

pytorch: use cpp17

```
  /opt/homebrew/Cellar/pytorch/2.1.0/include/torch/csrc/api/include/torch/all.h:4:2: error: C++17 or later compatible compiler is required to use PyTorch.
  #error C++17 or later compatible compiler is required to use PyTorch.
   ^
```

Signed-off-by: Rui Chen <rui@chenrui.dev>