clozure-cl: depend on x86_64
Upstream is not ready yet

ARM build currently fails with

In file included from ../lisp-exceptions.h:139:
  ../x86-exceptions.h:95:9: error: unknown type name 'x86_float_state64_t'
  typedef x86_float_state64_t native_float_state_t;
          ^
  ../x86-exceptions.h:98:9: error: unknown type name 'x86_exception_state64_t'; did you mean 'arm_exception_state64_t'?
  typedef x86_exception_state64_t native_exception_state_t;
          ^~~~~~~~~~~~~~~~~~~~~~~
          arm_exception_state64_t