solargraph: needs ruby 2.7+
```
  ERROR:  Error installing solargraph-0.49.0.gem:
  	The last version of rubocop (~> 1.38) to support your Ruby & RubyGems was 1.50.2. Try installing it with `gem install rubocop -v 1.50.2` and then running the current command again
  	rubocop requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
```

relates to https://github.com/Homebrew/homebrew-core/issues/142161#issuecomment-1752114211

Signed-off-by: Rui Chen <rui@chenrui.dev>