solr@8.11: fix flaky test
We need to sleep a little bit before asking for the status, to let time for solr to start

Might fix:

==> /opt/homebrew/Cellar/solr@8.11/8.11.2/bin/solr start -p 59094 -Djava.io.tmpdir=/tmp
==> /opt/homebrew/Cellar/solr@8.11/8.11.2/bin/solr status
Picked up _JAVA_OPTIONS: -Duser.home=/Users/rui/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp

ERROR: Failed to get system information from http://localhost:59094/solr due to: org.apache.solr.common.SolrException: Parse error : <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</title>
</head>