lilypond: fix build on macOS and fix test
Fixes:
Making lily/out/parser.o < cc
out/lexer.cc:6611:21: error: out-of-line definition of 'LexerInput' does not match any declaration in 'yyFlexLexer'
size_t yyFlexLexer::LexerInput( char* buf, size_t max_size )
                    ^~~~~~~~~~
out/lexer.cc:6638:19: error: out-of-line definition of 'LexerOutput' does not match any declaration in 'yyFlexLexer'
void yyFlexLexer::LexerOutput( const char* buf, size_t size )
                  ^~~~~~~~~~~
2 errors generated.

This happens because if flex is installed on your system, there will be a mixup between system and brewed flew on macOS.

Fixes also failing test
See https://gitlab.com/lilypond/lilypond/-/issues/6675