hopenpgp-tools: Fix build
Fixes:
Failed to build prettyprinter-convert-ansi-wl-pprint-1.1.2.
  Build log (
  /private/tmp/hopenpgp-tools-20230918-90300-lek9fz/hopenpgp-tools-0.23.7/.brew_home/.cache/cabal/logs/ghc-8.10.7/prttyprntr-cnvrt-ns-wl-pprnt-1.1.2-db86adc5.log
  ):
  Configuring library for prettyprinter-convert-ansi-wl-pprint-1.1.2..
  clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/usr/local/opt/ghc@8.10/lib' [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
  clang: warning: argument unused during compilation: '-L/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
  Preprocessing library for prettyprinter-convert-ansi-wl-pprint-1.1.2..
  Building library for prettyprinter-convert-ansi-wl-pprint-1.1.2..
  [1 of 2] Compiling Prettyprinter.Convert.AnsiWlPprint ( src/Prettyprinter/Convert/AnsiWlPprint.hs, dist/build/Prettyprinter/Convert/AnsiWlPprint.o, dist/build/Prettyprinter/Convert/AnsiWlPprint.dyn_o )

  src/Prettyprinter/Convert/AnsiWlPprint.hs:29:1: error:
      Could not find module ‘Text.PrettyPrint.ANSI.Leijen.Internal’
      Perhaps you meant
        Text.PrettyPrint.ANSI.Leijen (from ansi-wl-pprint-1.0.2)
        Text.PrettyPrint.ANSI.Leijen (needs flag -package-key prettyprinter-compat-ansi-wl-pprint-1.0.2)
      Use -v (or `:set -v` in ghci) to see a list of the files searched for.
     |
  29 | import qualified Text.PrettyPrint.ANSI.Leijen.Internal  as Old
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Error: cabal: Failed to build prettyprinter-convert-ansi-wl-pprint-1.1.2
  (which is required by exe:hot from hopenpgp-tools-0.23.7, exe:hokey from
  hopenpgp-tools-0.23.7 and others). See the build log above for details.