fb303: include `fbthrift` for test
```
/usr/local/Cellar/fb303/2023.10.23.00/include/fb303/thrift/gen-cpp2/BaseService.h:9:10: fatal error: 'thrift/lib/cpp2/gen/service_h.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

found in #152259
regression test, https://github.com/chenrui333/github-action-test/actions/runs/6659200739/job/18097771742

Signed-off-by: Rui Chen <rui@chenrui.dev>