graphqlviz 4.0.1 (new formula)
Signed-off-by: Rui Chen <rui@chenrui.dev>

graphqlviz: update test

fix linux test failure

```
  ==> /home/linuxbrew/.linuxbrew/Cellar/graphqlviz/4.0.1/bin/graphqlviz /tmp/graphqlviz-test-20231107-8494-zkhz2f/test.graphql
  (node:8502) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  ERROR: When run without a TTY; data must be provided in stdin
```

Signed-off-by: Rui Chen <rui@chenrui.dev>